### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by Lubmes** [jiren/flatpickr_rails#1]
Thanks for making this. 

How to localise? Adding `Flatpickr.localize(Flatpickr.l10ns.nl);` does not work. Not in the script on the page nor in the `application.js`.

Also, your docs should maybe state to restart the server after bundle. I know.. who forgets that ;)

And you repeat yourself in summing up of the styling options.

**Comment by jiren** [comment]
Only EN locals is available. I will add all available languages inf Flatpicker.

**Comment by pedantic-git** [comment]
Hi @Lubmes, @jiren - I've just created a PR #2 to update this to the latest version, which adds working L10n support as well as jQuery support and more themes.

**Comment by jiren** [comment]
Pushed new version 0.0.3 to rubygems.

**Comment by Lubmes** [comment]
Thanks for doing this. I got it working in Dutch :) Works really fine, also the base16_flat design works really well for me.
